function(generate_version_info _target)
    set(one_value_args
        # Required arguments
        PRODUCT_NAME COMPANY_NAME VERSION
        # Required in .rc file but filled automatically if not provided
        INTERNAL_NAME FILE_DESCRIPTION
        # Optional arguments
        COMMENTS COPYRIGHT TRADEMARKS PRIVATE_BUILD SPECIAL_BUILD VERSION_SUFFIX)
    cmake_parse_arguments(arg "" "${one_value_args}" "" ${ARGN})

    if(NOT arg_PRODUCT_NAME)
        message(FATAL_ERROR "No PRODUCT_NAME specified in generate_version_info(${_target})")
    endif()
    if(NOT arg_COMPANY_NAME)
        message(FATAL_ERROR "No COMPANY_NAME specified in generate_version_info(${_target})")
    endif()
    if(NOT arg_VERSION)
        message(FATAL_ERROR "No VERSION specified in generate_version_info(${_target})")
    endif()

    if(NOT arg_FILE_DESCRIPTION)
        set(arg_FILE_DESCRIPTION ${_target})
    endif()
    if(NOT arg_INTERNAL_NAME)
        set(arg_INTERNAL_NAME ${_target})
    endif()

    string(REPLACE "." ";" version_list ${arg_VERSION})
    list(LENGTH version_list version_num_components)
    list(GET version_list 0 version_major)
    if(version_num_components GREATER 1)
        list(GET version_list 1 version_minor)
    endif()
    if(version_num_components GREATER 2)
        list(GET version_list 2 version_patch)
    endif()
    if(version_num_components GREATER 3)
        list(GET version_list 3 version_build)
    endif()

    get_target_property(output_name ${_target} OUTPUT_NAME)
    if(NOT output_name)
        set(output_name ${_target})
    endif()
    get_target_property(target_type ${_target} TYPE)
    if(target_type STREQUAL "EXECUTABLE")
        set(VI_FILETYPE "VFT_APP")
        set(VI_ORIGINAL_FILENAME "${output_name}.exe")
    elseif(target_type STREQUAL "STATIC_LIBRARY")
        set(VI_FILETYPE "VFT_STATIC_LIB")
        set(VI_ORIGINAL_FILENAME "${output_name}.lib")
    else()
        set(VI_FILETYPE "VFT_DLL")
        set(VI_ORIGINAL_FILENAME "${output_name}.dll")
    endif()

    get_target_property(target_suffix ${_target} SUFFIX)
    if(NOT target_suffix STREQUAL "target_suffix-NOTFOUND")
        set(VI_ORIGINAL_FILENAME "${output_name}${target_suffix}")
    endif()

    set(file_version "${version_major}")
    set(file_version_str "${version_major}")
    if(DEFINED version_minor)
        string(APPEND file_version ",${version_minor}")
        string(APPEND file_version_str ".${version_minor}")
    else()
        string(APPEND file_version ",0")
    endif()
    if(DEFINED version_patch)
        string(APPEND file_version ",${version_patch}")
        string(APPEND file_version_str ".${version_patch}")
    else()
        string(APPEND file_version ",0")
    endif()
    if(DEFINED version_build)
        string(APPEND file_version ",${version_build}")
        string(APPEND file_version_str ".${version_build}")
    else()
        string(APPEND file_version ",0")
    endif()

    set(VI_PRODUCT_NAME "${arg_PRODUCT_NAME}")
    set(VI_COMPANY_NAME ${arg_COMPANY_NAME})
    set(VI_FILE_DESCRIPTION ${arg_FILE_DESCRIPTION})
    set(VI_INTERNAL_NAME ${arg_INTERNAL_NAME})

    set(VI_FILE_VERSION ${file_version})
    set(VI_PRODUCT_VERSION ${file_version})
    set(VI_FILE_VERSION_STR "${file_version_str}${arg_VERSION_SUFFIX}")
    set(VI_PRODUCT_VERSION_STR "${file_version_str}${arg_VERSION_SUFFIX}")

    if(arg_COMMENTS)
        set(VI_COMMENTS ${arg_COMMENTS})
    endif()
    if(arg_COPYRIGHT)
        set(VI_LEGAL_COPYRIGHT ${arg_COPYRIGHT})
    endif()
    if(arg_TRADEMARKS)
        set(VI_LEGAL_TRADEMARKS "${arg_TRADEMARKS}")
    endif()
    set(VI_FILE_FLAGS 0)
    if(arg_PRIVATE_BUILD)
        set(VI_PRIVATE_BUILD "${arg_PRIVATE_BUILD}")
        string(APPEND VI_FILE_FLAGS "|VS_FF_PRIVATEBUILD")
    endif()
    if(arg_SPECIAL_BUILD)
        set(VI_SPECIAL_BUILD "${arg_SPECIAL_BUILD}")
        string(APPEND VI_FILE_FLAGS "|VS_FF_SPECIALBUILD")
    endif()

    configure_file(
        ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/VersionInfo.rc.in
        ${CMAKE_CURRENT_BINARY_DIR}/VersionInfo.rc
        @ONLY
    )
    target_sources(${_target} PRIVATE ${CMAKE_CURRENT_BINARY_DIR}/VersionInfo.rc)
endfunction()
